log-level: info
external-controller: 0.0.0.0:9090
secret: ""
external-ui: ui
external-ui-url: "https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip"
unified-delay: true
ipv6: false
geodata-mode: true
find-process-mode: 'off'

profile:
  store-selected: true

sniffer:
  enable: true
  override-destination: false
  sniff:
    QUIC:
      ports: [443, 8443]
    TLS:
      ports: [443, 8443]
    HTTP:
      ports: [80, 8080-8880]
      override-destination: false

dns:
  enable: true
  cache-algorithm: arc
  prefer-h3: false
  use-system-hosts: false
  respect-rules: false
  listen: 0.0.0.0:53
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/15
  default-nameserver:
    - 8.8.8.8
    - 9.9.9.9
    - 1.1.1.1
  nameserver:
    - https://dns.google/dns-query#disable-qtype-65=true&disable-ipv6=true
    - https://cloudflare-dns.com/dns-query#disable-qtype-65=true&disable-ipv6=true
    - https://dns.quad9.net/dns-query#disable-qtype-65=true&disable-ipv6=true

hosts:
  dns.google: [8.8.8.8, 8.8.4.4]
  dns.quad9.net: [9.9.9.9, 149.112.112.112]
  cloudflare-dns.com: [104.16.248.249, 104.16.249.249]

listeners:
  - name: redir-in
    type: redir
    port: 12345
    listen: 0.0.0.0
  - name: tproxy-in
    type: tproxy
    port: 12346
    listen: 0.0.0.0
    udp: true
  - name: tun-in
    type: tun
    device: Meta
    inet4-address:
      - 100.64.0.1/32
    udp-timeout: 30
    mtu: 1500

proxies:

proxy-providers:

proxy-groups:
  - name: PROXY
    type: select
    proxies:
      - DIRECT

rule-providers:

rules:
  - GEOIP,private,DIRECT,no-resolve
  - MATCH,PROXY
